name: Skills
main: CyberTech\Main
version: 1.0.0.1
api: 1.0.0.1 

commands:
    skill:
        description: "Base Bounty Command"
        permission: skill
        useage: "/skill"
    myskill:
        description: "Shows Your Skills"
        permission: skill
        useage: "/myskill"
    xp:
        description: "Show How Much XP you have"
        permission: skill
        useage: "/xp"
    sheal:
        description: "Heals You"
        permission: skill
        useage: "/sheal"
        
permissions:
    skill:
        default: true
        description: "Only skill Permission"